#!/bin/bash

make -k

if [ ! -z `which valgrind` ]; then
valgrind --error-exitcode=1 ./tests
else
echo "SKIP: valgrind is not installed"
fi
s/ftests
if [ ! -z `which spawn-fcgi` ]; then
s/itests
else
echo "SKIP: spawn-fcgi is not installed"
fi
