#!/bin/bash
export ITEST_HOST=localhost
export ITEST_PORT=8080
export ITEST_PREFIX=/tmp/itest

set -e
make -k
itest/setup.sh
for test in itest/*.test ; do
	$test
    [ -e binlog ] && echo "$test creates binlog"
done
itest/teardown.sh
