#!/bin/bash
set -e

EXPECT="nginx version: nginx/1.2.1"
VERSION=$(/usr/sbin/nginx -v 2>&1)

if [ "$VERSION" != "$EXPECT" ] ; then
  echo "unknown $VERSION"
  if [ ! -d /var/log/nginx ]; then
    echo "Creating /var/log/nginx/"
    sudo mkdir -p /var/log/nginx
    sudo chmod 777 /var/log/nginx
  fi
fi
