#!/bin/bash
set -e

nginx_dirs=""

EXPECT="nginx version: nginx/1.2.1"
VERSION=$(/usr/sbin/nginx -v 2>&1)

if [ "$VERSION" != "$EXPECT" ] ; then
  echo "unknown $VERSION"
  nginx_dirs="/var/lib/nginx/ /var/log/nginx/"
fi

for dir in $nginx_dirs ; do
  if [ ! -d $dir ]; then
    echo "Creating $dir"
    sudo mkdir -p $dir
  fi
  sudo chmod 777 $dir
fi
